src/alphasite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    ),
]

src/blog/urls.py
from django.urls import path
from blog import views
from blog.feeds import LatestPostsFeed



app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

src/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            status=Post.Status.PUBLISHED
        )



class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', "Draft"
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User,
        related_name='blog_posts',
        on_delete=models.CASCADE
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

src/blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

src/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.db.models import Count
from django.conf import settings
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag

from blog.models import Post, Comment
from blog.forms import EmailPostForm, CommentForm, SearchForm

# Create your views here.



def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag
        }
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publish'
    )[:4]
    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )


def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read " \
                      f"{ post.title }"
            message = f"""
            Read {post.title} at {post_url}

            {cd['name']}'s comments:
                - "{cd['comments']}"
            """
            send_mail(
                subject,
                message,
                settings.EMAIL_HOST_USER,
                [cd['to']],
            )
            sent = True

    else:
        form = EmailPostForm()

    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        query = form.cleaned_data['query']
        results = Post.published.annotate(
            similarity=TrigramSimilarity('title', query)
        ).filter(similarity__gt=0.1).order_by('-similarity')
        # search_vector = SearchVector('title', weight='A') + search_vector('body', weight='B')
        # search_query = SearchQuery(query)
        # results = Post.published.annotate(
        #     search=search_vector,
        #     rank=SearchRank(search_vector, search_query)
        # ).filter(rank__gte=0.3).order_by()
    return render(
        request,
        'blog/post/search.html',

    )
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Post.published.annotate(
#                 search=SearchVector('title', 'body'),
#             ).filter(search=query)
#
#     return render(
#         request,
#         'blog/post/search.html',
#         {
#             'form': form,
#             'query': query,
#             'results': results
#         }
#     )

src/blog/templates/blog/_pagination.html
<nav class="pagination is-centered">
    {% if page.has_previous %}
    <a class="pagination-previous" href="?page={{ page.previous_page_number|stringformat:'d' }}{{ getvars }}{{ hashtag }}">Newer</a>
    {% else %}
    <a class="pagination-previous" disabled>Newer</a>
    {% endif %}

    {% if page.has_next %}
    <a class="pagination-next" href="?page={{ page.next_page_number|stringformat:'d' }}{{ getvars }}{{ hashtag }}">Older</a>
    {% else %}
    <a class="pagination-next" disabled>Older</a>
    {% endif %}

    <ul class="pagination-list">
        {% for p in page.page_range %}
        <li><a class="pagination-link{% if p == page.number %} is-current{% endif %}"
                href="?page={{ p|stringformat:'d' }}{{ getvars }}{{ hashtag }}">{{ p|stringformat:"d" }}
        </a></li>
        {% endfor %}
    </ul>
</nav>

src/blog/templates/blog/base.html
{% extends "bulma/base.html" %}
{% load static bulma_tags blog_tags %}
{% block css %}
    {% font_awesome %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extra_css %}
    <style>
    .indented {
        text-indent: 30px;
    }
    </style>
    {% endblock %}
{% endblock %}
{% block header %}
{% endblock %}
{% block hero %}
<section class="hero is-primary is-small">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item" href="{% url 'blog:post_list' %}">
                        <span>AlphaPattern Blog</span>
                    </a>
                    <div class="navbar-burger" data-target="navbarMenu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
                <div class="navbar-menu" id="navbarMenu">
                    <div class="navbar-end">
                        <a class="navbar-item" href="{% url 'blog:post_list' %}">Home</a>
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">Topics</a>
                            <div class="navbar-dropdown">
                                <a class="navbar-item" href="#">Topic</a>
                                <a class="navbar-item" href="#">Topic 2</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container">
            <div class="content has-text-centered">
                {% block hero_title %}
                {% endblock %}
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block content_area %}
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-9">
                {% block content %}
                {% endblock %}
            </div>
            <div class="column is-3">
                <div class="block box">
                    <p class="is-italic">This site now home to <strong>{% total_posts %}</strong> posts so far.</p>
                </div>
                <aside class="menu box">
                    {% show_latest_posts %}
                </aside>
                <hr>
                <aside class="menu box">
                    {% get_most_commented_posts as most_commented %}
                    <h4 class="menu-label">Popular</h4>
                    <ul class="menu-list">
                        {% for post in most_commented %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </aside>
                <aside class="menu box">
                    {% block sidenav %}
                    {% endblock %}
                </aside>
                <div class="buttons">
                    <a class="button is-block is-fullwidth is-dark is-outlined" href="{% url 'blog:post_feed' %}">Subscribe to RSS Feed</a>
                    <a class="button is-block is-fullwidth is-primary" href="#">Join the Newsletter</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block modal %}
{% endblock %}
{% block footer %}
<footer class="footer">
    <div class="container">
        <div class="content has-text-centered">
            <p>
                <strong>AlphaPattern</strong> built by <a href="https://github.com/HexChamber/">HexChamber DEV</a>.
            </p>
            <p>
                Source code is licensed by <a href="https://opensource.org/licenses/mit-license.php">MIT License</a>.
            </p>
            <p>
                &copy; 2024
            </p>
        </div>
    </div>
</footer>
{% endblock %}
{% block javascrip %}
{% block extra_javascript %}{% endblock %}
{% endblock %}

src/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% load bulma_tags %}
{% block title %}Add a comment{% endblock %}
{% block hero_title %}
<h1 class="title is-2 has-text-centered">
    Comment on <em>{{ post.title }}</em>
</h1>
{% endblock %}
{% block content %}
<div class="columns">
    <div class="column is-three-fifths">
        {% include "blog/post/includes/comment_form.html" %}
    </div>
</div>
{% endblock %}

src/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load bulma_tags blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block hero_title %}
<h1 class="title is-2 has-text-centered">{{ post.title }}</h1>
<p class="subtitle has-text-centered is-italic">Published {{ post.publish }} by {{ post.author.username }}</p>
{% endblock %}
{% block content %}
    <div class="box">
        <div class="block content">
            {{ post.body|indented|markdown }}
        </div>
        <div class="columns is-centered">
            <div class="column is-three-fifths">
                <div class="buttons is-centered">
                    <a class="button is-block is-fullwidth is-info" href="{% url 'blog:post_share' post.id %}">Share this Post</a>
                </div>
            </div>
        </div>
    </div>
    <div class="columns">
        <div class="column is-four_fifths">
            {% with comments.count as total_comments %}
            <h4 class="title has-text-centered has-text-weight-bold">
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h4>
            {% endwith %}
            {% for comment in comments %}
            <div class="card has-background-{% cycle 'primary-dark' 'primary' %} m-auto">
                <div class="card-header">
                    <div class="card-header-title">
                        {{ comment.name }}
                    </div>
                    <p class="subtitle has-text-weight-light is-italic is-size-7">@{{ comment.created }}</p>
                </div>
                <div class="card-content">
                    {{ comment.body|indented }}
                </div>
            </div>
            <br>
            {% empty %}
            <div class="message is-warning is-light">
                <div class="message-body">
                    <div class="content">
                        <p class="indented is-italic">There not yet any comments made for this post.</p>
                        <p>Be the first and comment with the form below!</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% resetcycle %}
            <br />
            <div class="columns">
                <div class="column is-two-thirds">
                    {% include "blog/post/includes/comment_form.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block sidenav %}
<h4 class="menu-label">Similar posts</h4>
<ul class="menu-list">
    {% for post in similar_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

src/blog/templates/blog/post/includes/comment_form.html
{% load bulma_tags %}
<div class="box">
    <form method="post" action="{% url 'blog:post_comment' post.id %}">
        {% csrf_token %}
        {{ form|bulma }}
        <div class="field is-right">
            <div class="control">
                <button type="submit" class="button is-primary">Add comment</button>
            </div>
        </div>
    </form>
</div>

src/blog/templates/blog/post/latest_posts.html
<h4 class="menu-label">Latest posts</h4>
<ul class="menu-list">
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

src/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static bulma_tags blog_tags %}
{% block title %}My Blog{% endblock %}

{% block hero_title %}
<h1 class="title">My Blog</h1>
{% if tag %}
<h3 class="subtitle is-size-5 has-text-weight-light">Posts for tag: <span class="tag is-light">{{ tag.name }}</span></h3>
{% endif %}
{% endblock %}
{% block content %}
{% for post in posts %}
<div class="card">
    <div class="card-header">
        <a class="card-header-title is-size-4" href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        <p class="has-text-weight-light is-italic subtitle is-size-7 mt-2 mr-2">
            Published {{ post.publish }} by {{ post.author.username }}
        </p>
    </div>
    <div class="card-content">
        <div class="tags is-right">
            {% for tag in post.tags.all %}
            <a class="tag is-{% cycle 'primary' 'dark' 'link' 'dark' %}" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% empty %}
            <div class="block"></div>
            {% endfor %}
        </div>
        <div class="content">
            {{ post.body|indented|markdown|truncatewords_html:30 }}
        </div>
    </div>
</div>
<br />
{% endfor %}
{% include "blog/_pagination.html" with page=posts %}
{% endblock %}

src/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags bulma_tags static %}
{% block title %}Search{% endblock %}
{% block hero_title %}
{% if query %}
<h1 class="title is-2 has-text-centered">
    Results for <em>{{ query }}</em>
</h1>
<p class="subtitle is-italic has-text-weight-light has-text-centered">
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</p>
{% else %}
<h1 class="title is-2 has-text-centered">
    Search for posts
</h1>
{% endif %}
{% endblock %}
{% block content %}
<div class="columns">
    <div class="column is-four-fifths">
        {% if query %}
            {% for post in results %}
            <article class="media box">
                <div class="media-content">
                    <div class="content">
                        <p>
                            <a class="has-text-weight-semibold" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </p>
                        <p>
                            <div class="tags is-right">
                                {% for tag in post.tags.all %}
                                <a class="tag is-{% cycle 'primary' 'dark' 'link' 'dark' %}" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                                {% endfor %}
                                {% resetcycle %}
                            </div>
                        </p>
                    </div>
                </div>
            </article>
            {% empty %}
            <div class="message is-warning">
                <div class="message-body">
                    <div class="content">
                        <p class="indented">Sorry, no results were found that match your query.</p>
                        <p class="is-italic">Please refine your search terms and try again.</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="box">
                <form method="get">
                    {% csrf_token %}
                    <div class="field has-addons">
                        <div class="control">
                            {{ form.query|bulma_inline }}
                        </div>
                        <div class="control">
                            <button type="submit" type="submit" class="button is-info">
                                Search
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load bulma_tags %}
{% block title %}Share this post{% endblock %}
{% block hero_title %}
{% if sent %}
<h1 class="title is-2 has-text-centered">
    <em>{{ post.title }}</em> shared
</h1>
<p class="subtitle has-text-centered">Post successfully shared to inbox</p>
{% else %}
<h1 class="title is-2 has-text-centered">
    Share <em>{{ post.title }} via e-mail
</h1>
<p class="subtitle has-text-centered">Send this post to a friend's inbox</p>
{% endif %}
{% endblock %}
{% block content %}
{% if sent %}
<div class="columns">
    <div class="column is-three-fifths">
        <div class="box">
            <div class="message is-success">
                <div class="message-body">
                    <p class="indented">An e-mail containing a link to <em>{{ post.title }}</em> along with your personal message have been
                    delivered to the inbox at <strong>{{ form.cleaned_data.to }}</strong>.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="columns">
    <div class="column is-three-fifths">
        <div class="box">
            <form method="post">
                {% csrf_token %}
                {{ form|bulma }}
                <div class="field">
                    <div class="control">
                        <button type="submit" class="button is-info is-block is-fullwidth">Share</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}